---
author: "Prashant Kalvapalle"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: 
  html_document:
  theme: flatly
toc: TRUE
toc_float: TRUE
title: "Timeseries:Liftstations_7-April-22"
---
  
```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = F, message = F, warning = F, fig.width = 12, fig.height = 4)

```

## Goal of the analysis

Visualizing timeseries of SARS CoV2-N1,N2 in Lift station samples, in comparison to their primary wastewater treatment plant. Data for N1, N2 and both replicate samples have been averaged before plotting.

Dates: March 2021 till 7-April-22

## Timeseries plots - Static

Y axis in units of copies per litre of WW

```{r all_plot}

all_plots <- 
  LS_WW_avg_nest %>% 
  
  mutate(
    plots = map2(data, # map the plot for each primary wwtp
                 Primary_WWTP, # this is used for labelling the plots
                 
                 ~ {plot_LS_time.series(.x) + 
                   
                   # for locations that have many LS, change the colour scheme that can accomodate > 8 colours
                   # 69 and Sims Bayou, and southwest..
                   {if( (.$Facility %>% unique() %>% length) > 8) scale_colour_viridis_d() else NULL} +
                   
                   # Add plot title
                   ggtitle(.y)} %>% 
                   
                   # print the plot
                   print()
                 )
        ) %>% 
  
  select(-data) # remove the data, to avoid redundancy and too much storage


# plotly::ggplotly(pltbox, dynamicTicks = TRUE)

```

## Interactive plots

```{r interactive_all}

large_wwtp_plots <- filter(all_plots, str_detect(Primary_WWTP, '69|SOUTHWEST|SIMS BAYOU'))

ggplotly(large_wwtp_plots$plots[[1]], dynamicTicks = TRUE)
ggplotly(large_wwtp_plots$plots[[2]], dynamicTicks = TRUE)
ggplotly(large_wwtp_plots$plots[[3]], dynamicTicks = TRUE)

# vectorized ggplotly does not work, only shows the static plot
# map(large_wwtp_plots$plots,
#       ~ ggplotly(.x, dynamicTicks = TRUE) %>% 
#       print())


```


```{r testing}

tst <- LS_WW_avg_nest$data[[1]]

plot_LS_time.series(tst) + scale_colour_viridis_d()

```
