---
title: "baylor vs ddpcr"
author: "Prashant Kalvapalle"
date: "8th Aug 2020"
output: 
  html_document:
    theme: flatly
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F, fig.width = 12)
```

## by WWTP

```{r cars}
# plotting
plt1 <- merge.data %>% ggplot(aes(WWTP, Copies_Per_Liter_WW, colour = Method)) + geom_point() + facet_grid(rows = vars(Target_Name), cols = vars(Week), scales = 'free_y') + ggtitle('713-715 Baylor ddPCR vs qPCR')

plt1 %>% format_logscale_y() %>% print()
```

## N1 vs N2 scatter plot


```{r pressure, echo=FALSE}

long_target <- merge.data %>% select(-Copies_per_uL_RNA, -Ct) %>% 
  pivot_wider(names_from = 'Target_Name', values_from = Copies_Per_Liter_WW)
  
plt2 <- long_target %>% ggplot(aes(`SARS CoV-2 N1`, `SARS CoV-2 N2`, fill = Method, colour = Method)) + 
  geom_point(shape = 19) +
  geom_point(shape = 21, colour = 'black', aes(alpha = Week)) + 
  scale_alpha_manual(values = c(0, 1)) +
  ggtitle('713-715 Baylor ddPCR vs qPCR', subtitle = 'Copies_Per_Liter_WW')

plt2 %>% format_logscale_x() %>% format_logscale_y() %>% print()
```

## ddPCR vs Baylor-qPCR

linearscale
```{r dd_vs_Bq}
long_method <- merge.data %>% select(WWTP_ID, Copies_Per_Liter_WW, Target_Name, Method, Week) %>% 
  pivot_wider(names_from = Method, values_from = Copies_Per_Liter_WW)

plt3 <- long_method %>% ggplot(aes(`R-ddPCR`, `B-qPCR`, colour = Target_Name)) + geom_point() + ggtitle('713-715 Baylor ddPCR vs qPCR', subtitle = 'Copies_Per_Liter_WW') + geom_smooth(method = lm) + geom_abline(slope = 1, intercept = 0) + 
  facet_grid(cols = vars(Week), scales = 'free_x')

# formula and linear regression
fmla <- as.formula(paste('`B-qPCR`', "~", '`R-ddPCR`'))
lin_reg_eqn <- long_method %>% group_by(Week, Target_Name) %>% group_map(~lm(fmla, data = .) %>% lm_eqn(.))

plt3 %>% print()
```

Log-log plot
```{r dd_vs_Bqlogs}

plt3 %>% format_logscale_x() %>% format_logscale_y() %>% print()
```

## Rice-qPCR vs Baylor-qPCR

linearscale
```{r Rq_vs_Bq}

plt3b <- long_method %>% ggplot(aes(`R-qPCR`, `B-qPCR`, colour = Target_Name)) + geom_point() + ggtitle('713-715 Baylor qPCR vs Rice qPCR on Baylor RNA extracts', subtitle = 'Copies_Per_Liter_WW') + geom_smooth(method = lm) + geom_abline(slope = 1, intercept = 0) + 
  facet_grid(cols = vars(Week), scales = 'free_x')

plt3b %>% format_logscale_x() %>% format_logscale_y() %>% print()

# formula and linear regression
fmla <- as.formula(paste('`B-qPCR`', "~", '`R-ddPCR`'))
lin_reg_eqn <- long_method %>% group_by(Week, Target_Name) %>% group_map(~lm(fmla, data = .) %>% lm_eqn(.))

```

Log-log plot
```{r Rq_vs_Bqlogs}

plt3 %>% format_logscale_x() %>% format_logscale_y() %>% print()
```

## ddPCR vs all qPCR
```{r dd_vs_allq}

long_method_bylab <- long_method %>% 
  pivot_longer(cols = contains('qPCR'), names_to = 'qPCR_lab', values_to = 'qPCR', names_pattern = '(.)-.*$')
  
plt4 <- long_method_bylab %>% ggplot(aes(`R-ddPCR`, `qPCR`, colour = qPCR_lab)) + geom_point() + ggtitle('713-715 Baylor ddPCR vs qPCR', subtitle = 'Copies_Per_Liter_WW') + geom_smooth(method = lm) + geom_abline(slope = 1, intercept = 0) + 
  facet_grid(rows = vars(Target_Name), cols = vars(Week), scales = 'free_x')

plt4 %>% print()

plt4 %>% format_logscale_x() %>% format_logscale_y() %>% print()

# plot_scatter(long_method %>% mutate(Sample_name = 0), colour_var = Target_Name, x_var = `R-ddPCR`, y_var = `B-qPCR`,  title_text = '713-715 Baylor ddPCR vs qPCR') %>% print()
```

