---
title: "0125 Chemagic-maxwell"
author: "Prashant Kalvapalle"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: 
  html_document:
    theme: flatly
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = F, message = F, warning = F, fig.width = 12, fig.height = 4)

```

## Goal of the analysis

Comparing CoV2 N1 N2 signals across the same wastewater samples between two different RNA extraction methods : Maxwell and Chemagic

```{r prelim}
# MAxwell vs chemagic for dd.WW117 : Head to head. Adhoc script. Need to run the prerequisites

source('./general_functions.R') # Source the general_functions file
title_name <- "0125 Chemagic-maxwell"

# input ----

dt.in <- read_sheet(sheeturls$complete_data, sheet = '0129 chmagic-maxwell+pavan')

# processing ----

dt.mid <- dt.in %>% 
  mutate(extraction_method = if_else(str_detect(Facility, '^C'), 'Chemagic', 'Maxwell'),
         concentration_factor = `Copies/ul RNA` * 1e6/`Copies/l WW`, # just for checking/for kathy's easy reference
         across(WWTP_ID, ~ str_remove(., '^C'))) %>%  # remove the C that identifies Chemagic
  filter(!str_detect(Facility, '^PR')) # remove Pavan's samples included in this plate
  
# polish for HHD/head to head analysis

present_WW_data <- dt.mid %>%
    
  rename('Copies_per_uL' = `Copies/ul RNA`,
         'Copies_Per_Liter_WW' = `Copies/l WW`,
         'Recovery_Rate' = `Percentage_recovery_BCoV`,
         Target_Name = `Target Name`) %>%
  select(-contains('Vol'), -`Spiked-in Copies/l WW`, -Tube_ID, -contains('Droplets')) %>% 
  select(WWTP_ID, extraction_method, concentration_factor, everything()) %>%  # order important columns first
    filter(!str_detect(WWTP_ID, 'DI|Blank|NTC')) # remove DI, BLANK and NTC controls

check_ok_and_write(present_only_WW, sheeturls$wwtp_only_data, title_name) # save results to a google sheet, ask for overwrite
write_csv(present_only_WW, path = str_c('excel files/Weekly data to HHD/', '0125 lift station Rice', '.csv'), na = '') # output csv file
    
```


## Plots

### (copies per l WW)

```{r wwplt}
plt.ww <-  {ggplot(dt.mid, aes(WWTP, `Copies/l WW`, colour = extraction_method)) +
  geom_point(size = 2) + 
    ggtitle('Copies per litre Wastewater', subtitle = 'Chemagic extraction vs Maxwell') + 
    geom_hline(aes(yintercept = Detection_Limit)) +
    facet_grid(~ `Target Name`)
} %>% 
  print()
  
```


### (copies per ul RNA)

```{r copiesrna}

plt.rna <-  {ggplot(dt.mid, aes(WWTP, `Copies/ul RNA`, colour = extraction_method)) +
    geom_point(size = 2) + 
    ggtitle('Copies per microlitre RNA', subtitle = 'Chemagic extraction vs Maxwell') + 
    facet_grid(~ `Target Name`)
} %>% 
  print()
  
```



### Scatter plots

### N1 vs N2 replicate

```{r maxchemcorr, fig.width=5, fig.height=5}

plot_scatter(.data = dt.mid, x_var = `Maxwell`, y_var = `Chemagic`, measure_var = 'Copies/l WW',
             colour_var = `Target Name`, grouping_var = `Target Name`,
             names_from_var = 'extraction_method',
             text_cols = c('Target Name', 'WWTP_ID'), extra_cols_for_pivot = NULL,
             sample_checking_column = WWTP_ID,
             text_for_equation = 'Rsquare') %>% 
  print()

```
### N1 - N2 combined

```{r maxchemcorrmerged, fig.width=5, fig.height=5}

plot_scatter(.data = dt.mid, x_var = `Maxwell`, y_var = `Chemagic`, measure_var = 'Copies/l WW',
             
             names_from_var = 'extraction_method',
             text_cols = c('Target Name', 'WWTP_ID'), extra_cols_for_pivot = NULL,
             sample_checking_column = WWTP_ID,
             text_for_equation = 'Rsquare') %>% 
  print()

```