---
title: "NTC_droplets"
author: "Prashant Kalvapalle"
date: '`r format(Sys.time(), "%d %B, %Y; %H:%M")`'
output: 
  html_document:
    theme: flatly
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = F, message = F, warning = F, fig.width = 12, fig.height = 4)
```

# NTC Positive droplets

## Static plot
```{r ntc}
plt_NTC <- {ggplot(ntc_dd.data, aes(Run_ID, Positives, colour = Target)) +
    geom_point() + 
    geom_line(aes(y = mean_positive))} %>% 
  format_classic() %>% 
  print()

```

## Interactive: NTC

```{r ntc.interactive}

plotly::ggplotly(plt_NTC, dynamicTicks = T)

```

## NTC Positive droplets above LOD of 3

```{r ntc3}

ntc_dd.data %>%
  filter(Positives > 3) %>% 
  mutate(mean_positive = mean(Positives)) %>% 

  {ggplot(., aes(Run_ID, Positives, colour = Target)) +
    geom_point() + 
    geom_line(aes(y = mean_positive))} %>% 
  format_classic() %>% 
  ggplotly(dynamicTicks = T)

```

## NTC Positive droplets: merging all targets

```{r ntcalltgt}

ntc_dd.data %>%
  # filter(Positives > 3) %>% 
  group_by(Run_ID) %>% 
  mutate(mean_positive = mean(Positives)) %>% 

  {ggplot(., aes(Run_ID, Positives)) +
    geom_point() + 
    geom_line(aes(y = mean_positive))} %>% 
  format_classic() %>% 
  ggplotly(dynamicTicks = T)

```
## NTC: merging all targets, > 3

```{r ntcalltgt0}

ntc_dd.data %>%
  filter(Positives > 3) %>%
  group_by(Run_ID) %>% 
  mutate(mean_positive = mean(Positives)) %>% 

  {ggplot(., aes(Run_ID, Positives)) +
    geom_point() + 
    geom_line(aes(y = mean_positive))} %>% 
  format_classic() %>% 
  ggplotly(dynamicTicks = T)

```

# Summary statistics

```{r summary}

ntc_dd.data %>% 
  summarise(across(Positives, lst(mean, median, sd)))
```
Statistics for Runs with > 3 droplets (assumed LOD)

```{r summary2}

ntc_more_than_3 <- ntc_dd.data %>% 
  filter(Positives > 3) %>% 
  mutate(mean_positive = mean(Positives)) 

ntc_more_than_3 %>% 
  summarise(across(Positives, lst(mean, median, sd)))
```

Fraction of runs with > 3 droplets (assumed LOD)

```{r summary3}

ntc_more_than_3 %>% 
  pull(Run_ID) %>% 
  unique() %>% 
  length() 

```
Fraction of runs with > 0 droplets

```{r summary0}

ntc_dd.data %>% 
  filter(Positives > 0) %>% 
  pull(Run_ID) %>% 
  unique() %>% 
  length() 

```
