---
title: "pMMoV-Timeseries"
author: "Kyle"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: 
  html_document:
    theme: flatly
    toc: TRUE
    toc_float: TRUE
---

**Description of plots:**
Light, smaller points show the individual replicates and the dark larger point show the mean


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = F, message = F, warning = F, fig.width = 10, fig.height = 10)
```

```{r Timeseries Plots}

# Create a directory to save individual plots
dir.create("individual_plots", showWarnings = FALSE)

# List to store individual plots
plot_list <- list()


# Define an extended color palette
extended_colors <- c("red", "blue", "green", "orange", "purple", "pink", "brown", "cyan", "magenta", "yellow", 
                     "darkgreen", "darkblue", "darkred", "darkorange", "darkpurple", "darkpink", "darkbrown", 
                     "darkcyan", "darkmagenta", "darkyellow")

# Loop through each WWTP
for (wwtp in unique(results_abs$WWTP)) {
  # Subset data for the specific WWTP
  subset_data <- results_abs[results_abs$WWTP == wwtp, ]
  
   # Convert Date_formatted to Date class
  subset_data$Date_formatted <- as.Date(subset_data$Date_formatted, format = "%m/%d/%y")


  # Create a timeseries plot
  p <- ggplot(subset_data, aes(x = Date_formatted, y = Copies_Per_Liter_WW, color = Run_week, shape = Positivity)) +
    geom_point() +
    geom_line(aes(group = Date_formatted)) +
    scale_shape_manual(values = c(Negative = 1, Positive = 19)) +
    scale_color_manual(values = extended_colors) +
    scale_y_log10(limits = c(1, 10000000)) +
    ylab("Log-transformed concentration \n (copies/L-wastewater)") +
    ggtitle(paste("Timeseries Plot for", wwtp)) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1), axis.title.x = element_blank())
  
  
      # Add vertical lines for specific dates and WWTPs
    if (wwtp %in% c("BRIE", "PARE")) {
    p <- p + geom_vline(xintercept = as.numeric(as.Date('10/05/23', format='%m/%d/%y')), linetype = "dashed")
  } else if (wwtp == "SCAE") {
    p <- p + geom_vline(xintercept = as.numeric(as.Date('10/24/23', format='%m/%d/%y')), linetype = "dashed")
  } else if (wwtp == "BURE") {
    p <- p + geom_vline(xintercept = as.numeric(as.Date('10/30/23', format='%m/%d/%y')), linetype = "dashed")
  } else if (wwtp == "SHAS") {
    p <- p + geom_vline(xintercept = as.numeric(as.Date('11/09/23', format='%m/%d/%y')), linetype = "dashed")
  } else if (wwtp %in% c("GOLE", "CORE")) {
    p <- p + geom_vline(xintercept = as.numeric(as.Date('11/13/23', format='%m/%d/%y')), linetype = "dashed")
  } else if (wwtp == "NORS") {
    p <- p + geom_vline(xintercept = as.numeric(as.Date('11/14/23', format='%m/%d/%y')), linetype = "dashed")
  }
  
  
  # Save the individual plot
  ggsave(paste0("individual_plots/", gsub("/", "_", wwtp), "_timeseries_plot.png"), plot = p)
  
  
  # Add the plot to the list
  plot_list[[wwtp]] <- p
}

# Set the file name for the multi-page PDF
pdf_file <- "combined_plots.pdf"

# Open a PDF device
pdf(pdf_file)

# Loop through the list of plots and print them to the PDF
lapply(plot_list, print)

# Close the PDF device
dev.off()
```
