---
title: "824 maxwell comparisons"
author: "Prashant Kalvapalle"
date: "31 August 2020"
output: 
  html_document:
    theme: flatly
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
library(knitr); library(plotly)
knitr::opts_chunk$set(echo = F, message = F, warning = F, fig.width = 10, fig.height = 4)

```
## Purpose

Compare maxwell data to Qiagen for the same WWTP samples from 824 week

## Superimposed plots


```{r OVERLAPS, echo=FALSE, fig.height= 6, fig.width= 14}

plt1 <- comb.data %>% ggplot(aes(WWTP, `Copies/l WW`, colour = RNA_extraction)) + 
  geom_point() + 
  # geom_line(alpha = .2, group = RNA_extraction) + 
  facet_wrap(~`Target Name`, nrow = 2)

plt1 %>% format_classic() %>% format_logscale_y() %>% print()

```


### Recovery rate
```{r reco_plot_overlap}

comb.data %>% 
  {ggplot(., aes(WWTP, `Recovery fraction`, colour = RNA_extraction)) + 
  geom_point()} %>% 
  format_classic() %>% 
  # format_logscale_y() %>% 
  print()

```

## Correlation plots

### Copies/l WW

Linear scale
```{r corr_copies}

wider_lm <- wider_data %>% 
  group_by(`Target Name`) %>% 
  nest(data = -`Target Name`) %>% 
  mutate(regression = map(data,
                            ~lm(`Copies/l WW_Maxwell` ~ `Copies/l WW_Qiagen`, data = .x)),
         reg_equation = map(regression,
                            ~lm_eqn(.x))) %>% 
  ungroup() %>% mutate(x_loc = c(3.5,3,5), y_loc = c(2,5,3), 
                       x_pos = c(5.5, 2.5, 2.5), y_pos = c(5.5, 3.4, 3.55)) %>% 
  select(-data, -regression)


plt2 <- wider_data %>% 
  ggplot(aes(`Copies/l WW_Qiagen`, `Copies/l WW_Maxwell`, colour = `Target Name`, label = Facility)) +
  geom_point() + 
  geom_smooth(method = 'lm', aes(fill = `Target Name`), alpha = .2) 
  # geom_text(data = wider_lm, aes(x = x_pos, y = y_pos, label = reg_equation, colour = `Target Name`), parse = T)

plt2 %>% print()  
```

Log-log scale plot

```{r corr_copies_log}
{plt2 + geom_text(data = wider_lm, aes(x = 10^x_loc, y = 10^y_loc, label = reg_equation, colour = `Target Name`), parse = T, hjust = 'inwards' )} %>% 
  format_logscale_x(.) %>% format_logscale_y() %>% 
  print()


plt2 %>% format_logscale_x() %>% format_logscale_y() %>% ggplotly(dynamicTicks = T, tooltip = 'label') #%>% 
  # add_annotations(x = wider_lm$x_pos, y = wider_lm$y_pos, colour = wider_lm$`Target Name`, text = 1:3)
```

### Recovery fraction

```{r corr_reco}

plt3 <- wider_data %>% 
  ggplot(aes(`Recovery fraction_Qiagen`, `Recovery fraction_Maxwell`, label = Facility)) +
  geom_point() + 
  # geom_text_repel() + 
  geom_smooth(method = 'lm', alpha = .2)

# plt3
plt3 %>% plotly::ggplotly(tooltip = 'label', dynamicTicks = T)
```

## Shred status

```{r shredo}

plt4 <- wider_data %>% 
  ggplot(aes(`Copies/l WW_Qiagen`, `Copies/l WW_Maxwell`, colour = Beads_shredding, label = Facility)) +
  geom_point() + 
  geom_smooth(method = 'lm', aes(fill = Beads_shredding), alpha = .2) + 
  scale_color_brewer(palette="YlOrRd") + scale_fill_brewer(palette="YlOrRd") + 
  
  facet_wrap(~`Target Name`, ncol = 3, scales = 'free') + 
  theme(legend.position = 'top') +
  ggtitle('Maxwell vs Qiagen', subtitle = 'Colour indicates the kit used and the shearing status of the Maxwell prep, Qiagen assumed w Qiagen kit w good shearing')

plt4 %>% format_logscale_x() %>% format_logscale_y() %>% print

plt4 %>% format_logscale_x() %>% format_logscale_y() %>% ggplotly(dynamicTicks = T, tooltip = 'label')
```

regression on Targets

```{r shredo_2}

plt5 <- wider_data %>% 
  ggplot(aes(`Copies/l WW_Qiagen`, `Copies/l WW_Maxwell`, colour = Beads_shredding, label = Facility)) +
  geom_point() + 
  geom_smooth(method = 'lm', aes(colour = NULL), alpha = .2) + 
  scale_color_brewer(palette="YlOrRd") + scale_fill_brewer(palette="YlOrRd") + 
  
  facet_wrap(~`Target Name`, ncol = 3, scales = 'free') + 
  theme(legend.position = 'top') +
  ggtitle('Maxwell vs Qiagen', subtitle = 'Colour indicates the kit used and the shearing status of the Maxwell prep, Qiagen assumed w Qiagen kit w good shearing')

plt5 %>% format_logscale_x() %>% format_logscale_y() %>% print

plt5 %>% format_logscale_x() %>% format_logscale_y() %>% ggplotly(dynamicTicks = T, tooltip = 'label')

```


## Removing outliers

Isopropanol samples removed

```{r no_iso_corr_copies_log}

# removing isopropanol
wider_filtered <- wider_data %>% 
  filter(!str_detect(Beads_shredding, 'Isopropyl'))

wider_lm_filtered <- wider_filtered %>% 
  group_by(`Target Name`) %>% 
  nest(data = -`Target Name`) %>% 
  mutate(regression = map(data,
                            ~lm(`Copies/l WW_Maxwell` ~ `Copies/l WW_Qiagen`, data = .x)),
         reg_equation = map(regression,
                            ~lm_eqn(.x))) %>% 
  ungroup() %>% mutate(x_loc = c(3.5,3,5), y_loc = c(2,5,3), 
                       x_pos = c(5.5, 2.5, 2.5), y_pos = c(5.5, 3.4, 3.55)) %>% 
  select(-data, -regression)


plt6 <- wider_filtered %>% 
  ggplot(aes(`Copies/l WW_Qiagen`, `Copies/l WW_Maxwell`, colour = `Target Name`, label = Facility)) +
  geom_point() + 
  geom_smooth(method = 'lm', aes(fill = `Target Name`), alpha = .2) 
  # geom_text(data = wider_lm_filtered, aes(x = x_pos, y = y_pos, label = reg_equation, colour = `Target Name`), parse = T)


{plt6 + geom_text(data = wider_lm_filtered, aes(x = 10^x_loc, y = 10^y_loc, label = reg_equation, colour = `Target Name`), parse = T, hjust = 'inwards' )} %>% 
  format_logscale_x(.) %>% format_logscale_y() %>% 
  print()


plt6 %>% format_logscale_x() %>% format_logscale_y() %>% ggplotly(dynamicTicks = T, tooltip = 'label') #%>% 
  # add_annotations(x = wider_lm_filtered$x_pos, y = wider_lm_filtered$y_pos, colour = wider_lm_filtered$`Target Name`, text = 1:3)
```



<!-- # old code archived -->
<!-- ```{r shredo_regression} -->


<!-- plt6 <- wider_data %>% -->
<!--   ggplot(aes(`Copies/l WW_Qiagen`, `Copies/l WW_Maxwell`, colour = `Target Name`, label = Facility)) + -->
<!--   geom_point() + -->
<!--   geom_smooth(method = 'lm', aes(fill = `Target Name`), alpha = .2) + -->

<!--   facet_wrap(~Beads_shredding, ncol = 3) + -->
<!--   theme(legend.position = 'top') + -->
<!--   ggtitle('Maxwell vs Qiagen', subtitle = 'Colour indicates the kit used and the shearing status of the Maxwell prep, Qiagen assumed w Qiagen kit w good shearing') -->

<!-- wider_lm_shred <- wider_data %>% -->
<!--   group_by(`Target Name`, Beads_shredding) %>% -->
<!--   nest(data = -c(`Target Name`, Beads_shredding)) %>% -->
<!--   mutate(regression = map(data, -->
<!--                             ~lm(`Copies/l WW_Maxwell` ~ `Copies/l WW_Qiagen`, data = .x)), -->
<!--          reg_equation = map(regression, -->
<!--                             ~lm_eqn(.x))) %>% -->
<!--   ungroup(by = `Target Name`) %>% mutate(x_loc = -Inf, y_loc = Inf - 100 * 0:2) %>% -->
<!--   select(-data, -regression) -->

<!-- plt6 %>% format_logscale_x() %>% format_logscale_y() %>% print -->

<!-- {plt6 + geom_text(data = wider_lm_shred, aes(x = 10^x_loc, y = 10^y_loc, label = reg_equation, colour = `Target Name`), parse = T, hjust = 'inwards' )} %>% -->
<!--   format_logscale_x(.) %>% format_logscale_y() %>% -->
<!--   print() -->

<!-- plt6 %>% format_logscale_x() %>% format_logscale_y() %>% ggplotly(dynamicTicks = T, tooltip = 'label') -->
<!-- ``` -->


